* Add data-base-url attribute in body tag closes #2051
zopefoundation/Products.CMFDefault pull request #1
Opened 2017-07-08 03:30 UTC by rodfersou

* Fix @@plone_lock_operations fixes #2061
* Review @@sharing fixes #2053

2017-07-08 14:41 UTC, tseaver requested changes

2017-07-08 14:41 UTC, tseaver commented on Products/CMFDefault/skins/ursine/main_template.pt
> +                  portal_url portal_state/portal_url"
The `@@plone_portal_state` view is not defined in CMFDefault.  Instead, used `globals/portal_url`.

2017-07-08 14:41 UTC, tseaver commented on Products/CMFDefault/skins/werebear/main_template.pt
> +                  portal_state context/@@plone_portal_state;
Ditto here.

2017-07-08 14:41 UTC, tseaver commented on Products/CMFDefault/skins/zpt_generic/main_template.pt
> +                  plone_view context/@@plone;
There is no `@@plone` view in CMFDefault.

2017-07-13 00:44 UTC, rodfersou commented on Products/CMFDefault/skins/zpt_generic/main_template.pt
> +                  plone_view context/@@plone;
I forgot this line.. going to remove

2017-07-13 00:51 UTC, rodfersou commented
@tseaver I'm on vacation this week.. I'll take a look at it next week if everything goes fine.

2017-07-21 18:44 UTC, rodfersou commented
@tseaver done

2017-07-21 19:22 UTC, tseaver approved these changes

2017-07-21 19:22 UTC, merged